export const GET_COURSE_LOADING = 'GET_COURSE_LOADING';
export const GET_COURSE_SUCCESS = 'GET_COURSE_SUCCESS';
export const GET_COURSE_FAILURE = 'GET_COURSE_FAILURE';
export const GET_STORED_COURSE_SUCCESS = 'GET_STORED_COURSE_SUCCESS';

export const GET_COURSES_LOADING = 'GET_COURSES_LOADING';
export const GET_COURSES_SUCCESS = 'GET_COURSES_SUCCESS';
export const GET_COURSES_FAILURE = 'GET_COURSES_FAILURE';

export const ADD_COURSE_LOADING = 'ADD_COURSE_LOADING';
export const ADD_COURSE_SUCCESS = 'ADD_COURSE_SUCCESS';
export const ADD_COURSE_FAILURE = 'ADD_COURSE_FAILURE';

export const DELETE_COURSE_LOADING = 'DELETE_COURSE_LOADING';
export const DELETE_COURSE_SUCCESS = 'DELETE_COURSE_SUCCESS';
export const DELETE_COURSE_FAILURE = 'DELETE_COURSE_FAILURE';
export const EDIT_COURSE_LOADING = 'EDIT_COURSE_LOADING';
export const EDIT_COURSE_SUCCESS = 'EDIT_COURSE_SUCCESS';
export const EDIT_COURSE_FAILURE = 'EDIT_COURSE_FAILURE';
export const GET_STATS_LOADING = 'GET_STATS_LOADING';
export const GET_STATS_SUCCESS = 'GET_STATS_SUCCESS';
export const GET_STATS_FAILURE = 'GET_STATS_FAILURE';
